
const cmds = new Array(
"<a name=\"aaa\"></a>",
"cmds_a.html#addgroup=addgroup",
"cmds_a.html#adduser=adduser",
"apache.html=APACHE",
"cmds_a.html#apropos=apropos",
"cmds_a.html#apt=apt",
"cmds_a.html#apt-get=apt-get",
"cmds_a.html#arp=arp",
"cmds_a.html#at=at",
"cmds_a.html#at=atq",
"cmds_a.html#at=atrm",
"audio.html=AUDIO",
"<a name=\"bbb\"></a>",
"cmds_b.html#badblocks=badblocks",
"cmds_b.html#base64=base64",
"bash.html=BASH",
"cmds_a.html#at=batch",
"binutils.html=BINUTILS",
"boot.html=BOOT",
"cmds_b.html#bzip2=bzip2",
"<a name=\"ccc\"></a>",
"cmds_c.html#cat=cat",
"cmds_c.html#cd=cd",
"cmds_c.html#chattr=chattr",
"cmds_c.html#chgrp=chgrp",
"cmds_c.html#chkconfig=chkconfig",
"cmds_c.html#chmod=chmod",
"cmds_c.html#chown=chown",
"cmds_c.html#cksum=cksum",
"cmds_c.html#cmp=cmp",
"cmds_c.html#comm=comm",
"coreutils.html=COREUTILS",
"cmds_c.html#cp=cp",
"cmds_c.html#cpio=cpio",
"cmds_c.html#crontab=crontab",
"cmds_c.html#curl=curl",
"<a name=\"ddd\"></a>",
"cmds_d.html#date=date",
"cmds_d.html#dd=dd",
"cmds_d.html#ddrescue=ddrescue",
"cmds_d.html#df=df",
"cmds_d.html#diff=diff",
"cmds_d.html#dig=dig",
"cmds_d.html#dos2unix=dos2unix",
"cmds_d.html#du=du",
"cmds_d.html#dumpe2fs=dumpe2fs",
"<a name=\"eee\"></a>",
"cmds_e.html#e2fsck=e2fsck",
"cmds_e.html#e2label=e2label",
"cmds_g.html#grep=egrep",
"cmds_e.html#env=env",
"cmds_e.html#ethtool=ethtool",
"cmds_e.html#expand=expand",
"<a name=\"fff\"></a>",
"cmds_f.html#fdisk=fdisk",
"video.html=ffmpeg",
"cmds_g.html#grep=fgrep",
"cmds_f.html#file=file",
"cmds_f.html#find=find",
"cmds_f.html#free=free",
"cmds_f.html#fromdos=fromdos",
"cmds_f.html#fsck=fsck",
"cmds_f.html#fuser=fuser",
"<a name=\"ggg\"></a>",
"cmds_g.html#gdisk=gdisk",
"cmds_g.html#gpg=gpg",
"cmds_g.html#gpgv=gpgv",
"cmds_g.html#grep=grep",
"cmds_g.html#groupadd=groupadd",
"cmds_g.html#groupdel=groupdel",
"cmds_g.html#groupmod=groupmod",
"cmds_g.html#groups=groups",
"cmds_p.html#pwconv=grpconv",
"cmds_p.html#pwconv=grpunconv",
"cmds_g.html#gzip=gunzip",
"cmds_g.html#gzip=gzip",
"<a name=\"hhh\"></a>",
"cmds_s.html#shutdown=halt",
"cmds_h.html#hddtemp=hddtemp",
"cmds_h.html#head=head",
"cmds_h.html#hexdump=hexdump",
"cmds_h.html#history=history",
"cmds_h.html#host=host",
"cmds_h.html#hostname=hostname",
"cmds_h.html#htop=htop",
"cmds_h.html#hwclock=hwclock",
"<a name=\"iii\"></a>",
"cmds_i.html#iconv=iconv",
"cmds_i.html#id=id",
"cmds_i.html#ifconfig=ifconfig",
"cmds_i.html#info=info",
"cmds_i.html#init=init",
"cmds_i.html#initctl=initctl",
"sw_inst.html=INSTALL",
"cmds_i.html#ip=ip",
"cmds_i.html#ipcs=ipcs",
"cmds_i.html#iptables=iptables",
"cmds_i.html#iw=iw",
"cmds_i.html#iwconfig=iwconfig",
"cmds_i.html#iwlist=iwlist",
"cmds_i.html#iwspy=iwspy",
"<a name=\"jjj\"></a>",
"cmds_i.html#jobs=jobs",
"<a name=\"kkk\"></a>",
"kernel.html=KERNEL",
"keys.html=KEYS",
"cmds_k.html#kill=kill",
"cmds_k.html#killall=killall",
"<a name=\"lll\"></a>",
"cmds_l.html#lastlog=lastlog",
"cmds_l.html#less=less",
"live_usb.html=Live_USB",
"cmds_l.html#ln=ln",
"cmds_l.html#ls=ls",
"cmds_l.html#lsattr=lsattr",
"cmds_l.html#lshw=lshw",
"cmds_l.html#lsof=lsof",
"cmds_l.html#lspci=lspci",
"cmds_l.html#lsusb=lsusb",
"<a name=\"mmm\"></a>",
"cmds_m.html#mail=mail",
"postfix-dovecot.html=MAIL_SVC",
"cmds_m.html#man=man",
"cmds_m.html#mc=mc",
"misc.html=MISCELL",
"cmds_m.html#mkdir=mkdir",
"cmds_m.html#mke2fs=mke2fs",
"cmds_m.html#mkfs=mkfs",
"cmds_m.html#mklost+found=mklost+found",
"cmds_m.html#mknod=mknod",
"cmds_m.html#mkswap=mkswap",
"cmds_m.html#mktemp=mktemp",
"cmds_m.html#modinfo=modinfo",
"cmds_m.html#modprobe=modprobe",
"cmds_m.html#mount=mount",
"video.html#mplayer=mplayer",
"cmds_m.html#mtr=mtr",
"video.html=MULTIMEDIA",
"cmds_m.html#mv=mv",
"mysql.html=MySQL",
"<a name=\"nnn\"></a>",
"net.html=NET",
"cmds_n.html#netcat=nc",
"cmds_n.html#netcat=netcat",
"cmds_n.html#netstat=netstat",
"cmds_n.html#nice=nice",
"cmds_n.html#nmap=nmap",
"cmds_n.html#nmcli=nmcli",
"cmds_n.html#nproc=nproc",
"cmds_n.html#ntpd=ntpd",
"cmds_n.html#ntpd=ntpdate",
"cmds_n.html#ntpd=ntpq",
"cmds_n.html#ntsysv=ntsysv",
"<a name=\"ooo\"></a>",
"cmds_o.html#od=od",
"oldstuff.html=OLD_STUFF",
"cmds_o.html#openssl=openssl",
"<a name=\"ppp\"></a>",
"cmds_p.html#pacmd=pacmd",
"cmds_p.html#passwd=passwd",
"cmds_p.html#pgrep=pgrep",
"cmds_p.html#pidof=pidof",
"cmds_p.html#ping=ping",
"cmds_p.html#pgrep=pkill",
"psql.html=PostgreSQL",
"cmds_p.html#postfix=postfix",
"cmds_s.html#shutdown=poweroff",
"cmds_p.html#printf=printf",
"programming.html=PROG",
"cmds_p.html#ps=ps",
"cmds_p.html#pstree=pstree",
"cmds_p.html#pwck=pwck",
"cmds_p.html#pwconv=pwconv",
"cmds_p.html#pwd=pwd",
"cmds_p.html#pwconv=pwunconv",
"<a name=\"rrr\"></a>",
"cmds_s.html#shutdown=reboot",
"regexp.html=REGEX",
"cmds_r.html#rename=rename",
"cmds_r.html#renice=renice",
"cmds_r.html#rm=rm",
"cmds_r.html#rmdir=rmdir",
"cmds_r.html#route=route",
"cmds_r.html#rpm=rpm",
"cmds_r.html#rsync=rsync",
"<a name=\"sss\"></a>",
"cmds_s.html#sed=sed",
"cmds_s.html#sfdisk=sfdisk",
"cmds_s.html#sha256sum=sha256sum",
"cmds_s.html#showmount=showmount",
"cmds_s.html#shutdown=shutdown",
"cmds_s.html#sleep=sleep",
"cmds_s.html#slocate=slocate",
"cmds_s.html#smartctl=smartctl",
"cmds_s.html#sort=sort",
"cmds_s.html#split=split",
"cmds_s.html#ss=ss",
"storage.html#ssd=SSD",
"cmds_s.html#ssh=ssh",
"cmds_s.html#stat=stat",
"storage.html=STORAGE",
"cmds_s.html#strace=strace",
"cmds_s.html#su=su",
"cmds_s.html#sudo=sudo",
"cmds_s.html#swapon=swapon",
"cmds_s.html#swapon=swapoff",
"cmds_s.html#sysctl=sysctl",
"system.html=SYSTEM",
"cmds_s.html#systemctl=systemctl",
"boot.html#init=systemd",
"<a name=\"ttt\"></a>",
"cmds_t.html#tail=tail",
"cmds_t.html#tar=tar",
"tcpip.html=TCP/IP",
"cmds_t.html#tee=tee",
"cmds_t.html#time=time",
"cmds_t.html#tmpwatch=tmpwatch",
"cmds_f.html#fromdos=todos",
"cmds_t.html#top=top",
"cmds_t.html#touch=touch",
"cmds_t.html#traceroute=traceroute",
"cmds_t.html#tune2fs=tune2fs",
"<a name=\"uuu\"></a>",
"cmds_u.html#umount=umount",
"cmds_u.html#uname=uname",
"cmds_u.html#unexpand=unexpand",
"cmds_u.html#uniq=uniq",
"cmds_d.html#dos2unix=unix2dos",
"cmds_u.html#unzip=unzip",
"storage.html#usb=USB",
"cmds_u.html#useradd=useradd",
"cmds_u.html#userdel=userdel",
"cmds_u.html#usermod=usermod",
"util-linux.html=Util-Linux",
"cmds_u.html#uuidgen=uuidgen",
"<a name=\"vvv\"></a>",
"cmds_v.html#vi=vi",
"video.html=VIDEO",
"virt.html=VIRT",
"cmds_v.html#visudo=visudo",
"cmds_v.html#vmstat=vmstat",
"<a name=\"www\"></a>",
"cmds_w.html#w=w",
"cmds_w.html#wc=wc",
"cmds_w.html#wget=wget",
"cmds_w.html#whatis=whatis",
"cmds_w.html#whereis=whereis",
"cmds_w.html#which=which",
"cmds_w.html#who=who",
"<a name=\"yyy\"></a>",
"cmds_y.html#yes=yes",
"cmds_y.html#yum=yum",
"<a name=\"zzz\"></a>",
"cmds_g.html#gzip=zcat",
"cmds_z.html#zip=zip");


var makeFrameToc = function() {
  const strTarget = " target=\"frame2\""

  document.write("<p class=\"toc3\">\n");

  for (let x in cmds) {
    if ( cmds[x].substring(0, 7) == '<a name') {
      document.write(cmds[x]);
    } else {
      let strTemp = cmds[x].replace("=", "\"" + strTarget + "\">");
      document.write("<a href=\"" + strTemp + "</a>\n");
    }
  }
  document.write("</p>\n");
}


var makeOneColToc = function() {
  document.write("<p class=\"toc3\">\n");

  for (let x in cmds) {
    if ( cmds[x].substring(0, 7) == '<a name') {
      document.write(cmds[x]);
    } else {
      let strTemp = cmds[x].replace("=", "\">");
      document.write("<a href=\"" + strTemp + "</a>\n");
    }
  }
  document.write("</p>\n");
}


var makeMobileToc = function() {
  document.write("<p class=\"toc4\">\n");

  for (let x in cmds) {
    if ( cmds[x].substring(0, 7) == '<a name') {
      document.write(cmds[x]);
    } else {
      let strTemp = cmds[x].replace("=", "\">");
      document.write("<a href=\"" + strTemp + "</a>\n");
    }
  }
  document.write("</p>\n");
}

// -END -
